
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.me.xdf.webservice.client.ad;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-03-14T19:37:39.573+08:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ADApi",
                      portName = "ADApiSoap",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://192.168.1.12:866/ADApi.asmx?wsdl",
                      endpointInterface = "ADApiSoap")
                      
public class ADApiSoapImpl implements ADApiSoap {

    private static final Logger LOG = Logger.getLogger(ADApiSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see ADApiSoap#updateUserthumbnailphotoV2(java.lang.String  accountID ,)byte[]  thumbnailphoto ,)java.lang.String  systemTag ,)java.lang.String  sign )*
     */
    @Override
	public StateInfo updateUserthumbnailphotoV2(String accountID,byte[] thumbnailphoto,String systemTag,String sign) {
        LOG.info("Executing operation updateUserthumbnailphotoV2");
        System.out.println(accountID);
        System.out.println(thumbnailphoto);
        System.out.println(systemTag);
        System.out.println(sign);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage-1126183491");
            _return.setState(113315937);
            _return.setIExit(1571079179);
            _return.setSExit("SExit720476551");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#addADAccountForTemp(UserInfo  userInfo )*
     */
    @Override
	public StateInfo addADAccountForTemp(UserInfo userInfo) { 
        LOG.info("Executing operation addADAccountForTemp");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage1428246171");
            _return.setState(2107401042);
            _return.setIExit(-290980218);
            _return.setSExit("SExit1198392786");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#helloWorld(*
     */
    @Override
	public String helloWorld() {
        LOG.info("Executing operation helloWorld");
        try {
            String _return = "_return288519599";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#getUserThumbnailphoto(UserInfo  userInfo )*
     */
    @Override
	public byte[] getUserThumbnailphoto(UserInfo userInfo) { 
        LOG.info("Executing operation getUserThumbnailphoto");
        System.out.println(userInfo);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#updateUserPhone(UserInfo  userInfo )*
     */
    @Override
	public StateInfo updateUserPhone(UserInfo userInfo) { 
        LOG.info("Executing operation updateUserPhone");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage1584593393");
            _return.setState(-607933453);
            _return.setIExit(1263068482);
            _return.setSExit("SExit-1265228096");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#disabledUser(UserInfo  userInfo )*
     */
    @Override
	public StateInfo disabledUser(UserInfo userInfo) { 
        LOG.info("Executing operation disabledUser");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage-1777805103");
            _return.setState(1330155025);
            _return.setIExit(1810580833);
            _return.setSExit("SExit-1645947607");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#updateUserthumbnailphoto(UserInfo  userInfo )*
     */
    @Override
	public StateInfo updateUserthumbnailphoto(UserInfo userInfo) { 
        LOG.info("Executing operation updateUserthumbnailphoto");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage-980586058");
            _return.setState(1194527364);
            _return.setIExit(1491727319);
            _return.setSExit("SExit1484530127");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#changePWD(java.lang.String  accountID ,)java.lang.String  oldPWD ,)java.lang.String  newPWD ,)java.lang.String  systemTag ,)java.lang.String  sign )*
     */
    @Override
	public StateInfo changePWD(String accountID,String oldPWD,String newPWD,String systemTag,String sign) {
        LOG.info("Executing operation changePWD");
        System.out.println(accountID);
        System.out.println(oldPWD);
        System.out.println(newPWD);
        System.out.println(systemTag);
        System.out.println(sign);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage1195056248");
            _return.setState(-35750933);
            _return.setIExit(27720680);
            _return.setSExit("SExit112583758");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#openMail(UserInfo  userInfo )*
     */
    @Override
	public StateInfo openMail(UserInfo userInfo) { 
        LOG.info("Executing operation openMail");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage1845148205");
            _return.setState(-1535901646);
            _return.setIExit(-1857095616);
            _return.setSExit("SExit-1662381195");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ADApiSoap#updateUser(UserInfo  userInfo )*
     */
    @Override
	public StateInfo updateUser(UserInfo userInfo) { 
        LOG.info("Executing operation updateUser");
        System.out.println(userInfo);
        try {
            StateInfo _return = new StateInfo();
            ExtensionDataObject _returnExtensionData = new ExtensionDataObject();
            _return.setExtensionData(_returnExtensionData);
            _return.setErrMessage("ErrMessage1056695942");
            _return.setState(1699174436);
            _return.setIExit(1437809906);
            _return.setSExit("SExit1640120564");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
