package cn.me.xdf.webservice.client.ad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-11T16:12:44.210+08:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ADApiSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ADApiSoap {

    @WebResult(name = "UpdateUserthumbnailphotoV2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserthumbnailphotoV2", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserthumbnailphotoV2")
    @WebMethod(operationName = "UpdateUserthumbnailphotoV2", action = "http://tempuri.org/UpdateUserthumbnailphotoV2")
    @ResponseWrapper(localName = "UpdateUserthumbnailphotoV2Response", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserthumbnailphotoV2Response")
    public cn.me.xdf.webservice.client.ad.StateInfo updateUserthumbnailphotoV2(
            @WebParam(name = "AccountID", targetNamespace = "http://tempuri.org/")
            String accountID,
            @WebParam(name = "Thumbnailphoto", targetNamespace = "http://tempuri.org/")
            byte[] thumbnailphoto,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "AddADAccountForTempResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddADAccountForTemp", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.AddADAccountForTemp")
    @WebMethod(operationName = "AddADAccountForTemp", action = "http://tempuri.org/AddADAccountForTemp")
    @ResponseWrapper(localName = "AddADAccountForTempResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.AddADAccountForTempResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo addADAccountForTemp(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.HelloWorldResponse")
    public String helloWorld();

    @WebResult(name = "GetUserThumbnailphotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserThumbnailphoto", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetUserThumbnailphoto")
    @WebMethod(operationName = "GetUserThumbnailphoto", action = "http://tempuri.org/GetUserThumbnailphoto")
    @ResponseWrapper(localName = "GetUserThumbnailphotoResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetUserThumbnailphotoResponse")
    public byte[] getUserThumbnailphoto(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "UpdateUserPhoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserPhone", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserPhone")
    @WebMethod(operationName = "UpdateUserPhone", action = "http://tempuri.org/UpdateUserPhone")
    @ResponseWrapper(localName = "UpdateUserPhoneResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserPhoneResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo updateUserPhone(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "DisabledUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DisabledUser", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.DisabledUser")
    @WebMethod(operationName = "DisabledUser", action = "http://tempuri.org/DisabledUser")
    @ResponseWrapper(localName = "DisabledUserResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.DisabledUserResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo disabledUser(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "UpdateUserthumbnailphotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserthumbnailphoto", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserthumbnailphoto")
    @WebMethod(operationName = "UpdateUserthumbnailphoto", action = "http://tempuri.org/UpdateUserthumbnailphoto")
    @ResponseWrapper(localName = "UpdateUserthumbnailphotoResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserthumbnailphotoResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo updateUserthumbnailphoto(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "GetUserInfoByCnResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserInfoByCn", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetUserInfoByCn")
    @WebMethod(operationName = "GetUserInfoByCn", action = "http://tempuri.org/GetUserInfoByCn")
    @ResponseWrapper(localName = "GetUserInfoByCnResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetUserInfoByCnResponse")
    public cn.me.xdf.webservice.client.ad.ArrayOfUserInfo getUserInfoByCn(
            @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
            String accountId,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "EnableUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnableUser", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.EnableUser")
    @WebMethod(operationName = "EnableUser", action = "http://tempuri.org/EnableUser")
    @ResponseWrapper(localName = "EnableUserResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.EnableUserResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo enableUser(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "GetGroupToUserListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGroupToUserList", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetGroupToUserList")
    @WebMethod(operationName = "GetGroupToUserList", action = "http://tempuri.org/GetGroupToUserList")
    @ResponseWrapper(localName = "GetGroupToUserListResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.GetGroupToUserListResponse")
    public cn.me.xdf.webservice.client.ad.ArrayOfString getGroupToUserList(
            @WebParam(name = "GroupAccountName", targetNamespace = "http://tempuri.org/")
            String groupAccountName,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "ChangePWDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangePWD", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.ChangePWD")
    @WebMethod(operationName = "ChangePWD", action = "http://tempuri.org/ChangePWD")
    @ResponseWrapper(localName = "ChangePWDResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.ChangePWDResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo changePWD(
            @WebParam(name = "AccountID", targetNamespace = "http://tempuri.org/")
            String accountID,
            @WebParam(name = "OldPWD", targetNamespace = "http://tempuri.org/")
            String oldPWD,
            @WebParam(name = "NewPWD", targetNamespace = "http://tempuri.org/")
            String newPWD,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "OpenMailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OpenMail", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.OpenMail")
    @WebMethod(operationName = "OpenMail", action = "http://tempuri.org/OpenMail")
    @ResponseWrapper(localName = "OpenMailResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.OpenMailResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo openMail(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );

    @WebResult(name = "UpdateUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUser")
    @WebMethod(operationName = "UpdateUser", action = "http://tempuri.org/UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://tempuri.org/", className = "cn.me.xdf.webservice.client.ad.UpdateUserResponse")
    public cn.me.xdf.webservice.client.ad.StateInfo updateUser(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            cn.me.xdf.webservice.client.ad.UserInfo userInfo
    );
}
