package cn.me.xdf.webservice.client.ad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-03-14T19:37:39.603+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ADApiSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ADApiSoap {

    @WebResult(name = "UpdateUserthumbnailphotoV2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserthumbnailphotoV2", targetNamespace = "http://tempuri.org/", className = "UpdateUserthumbnailphotoV2")
    @WebMethod(operationName = "UpdateUserthumbnailphotoV2", action = "http://tempuri.org/UpdateUserthumbnailphotoV2")
    @ResponseWrapper(localName = "UpdateUserthumbnailphotoV2Response", targetNamespace = "http://tempuri.org/", className = "UpdateUserthumbnailphotoV2Response")
    public StateInfo updateUserthumbnailphotoV2(
            @WebParam(name = "AccountID", targetNamespace = "http://tempuri.org/")
            String accountID,
            @WebParam(name = "Thumbnailphoto", targetNamespace = "http://tempuri.org/")
            byte[] thumbnailphoto,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "AddADAccountForTempResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddADAccountForTemp", targetNamespace = "http://tempuri.org/", className = "AddADAccountForTemp")
    @WebMethod(operationName = "AddADAccountForTemp", action = "http://tempuri.org/AddADAccountForTemp")
    @ResponseWrapper(localName = "AddADAccountForTempResponse", targetNamespace = "http://tempuri.org/", className = "AddADAccountForTempResponse")
    public StateInfo addADAccountForTemp(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "HelloWorldResponse")
    public String helloWorld();

    @WebResult(name = "GetUserThumbnailphotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserThumbnailphoto", targetNamespace = "http://tempuri.org/", className = "GetUserThumbnailphoto")
    @WebMethod(operationName = "GetUserThumbnailphoto", action = "http://tempuri.org/GetUserThumbnailphoto")
    @ResponseWrapper(localName = "GetUserThumbnailphotoResponse", targetNamespace = "http://tempuri.org/", className = "GetUserThumbnailphotoResponse")
    public byte[] getUserThumbnailphoto(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "UpdateUserPhoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserPhone", targetNamespace = "http://tempuri.org/", className = "UpdateUserPhone")
    @WebMethod(operationName = "UpdateUserPhone", action = "http://tempuri.org/UpdateUserPhone")
    @ResponseWrapper(localName = "UpdateUserPhoneResponse", targetNamespace = "http://tempuri.org/", className = "UpdateUserPhoneResponse")
    public StateInfo updateUserPhone(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "DisabledUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DisabledUser", targetNamespace = "http://tempuri.org/", className = "DisabledUser")
    @WebMethod(operationName = "DisabledUser", action = "http://tempuri.org/DisabledUser")
    @ResponseWrapper(localName = "DisabledUserResponse", targetNamespace = "http://tempuri.org/", className = "DisabledUserResponse")
    public StateInfo disabledUser(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "UpdateUserthumbnailphotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserthumbnailphoto", targetNamespace = "http://tempuri.org/", className = "UpdateUserthumbnailphoto")
    @WebMethod(operationName = "UpdateUserthumbnailphoto", action = "http://tempuri.org/UpdateUserthumbnailphoto")
    @ResponseWrapper(localName = "UpdateUserthumbnailphotoResponse", targetNamespace = "http://tempuri.org/", className = "UpdateUserthumbnailphotoResponse")
    public StateInfo updateUserthumbnailphoto(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "ChangePWDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangePWD", targetNamespace = "http://tempuri.org/", className = "ChangePWD")
    @WebMethod(operationName = "ChangePWD", action = "http://tempuri.org/ChangePWD")
    @ResponseWrapper(localName = "ChangePWDResponse", targetNamespace = "http://tempuri.org/", className = "ChangePWDResponse")
    public StateInfo changePWD(
            @WebParam(name = "AccountID", targetNamespace = "http://tempuri.org/")
            String accountID,
            @WebParam(name = "OldPWD", targetNamespace = "http://tempuri.org/")
            String oldPWD,
            @WebParam(name = "NewPWD", targetNamespace = "http://tempuri.org/")
            String newPWD,
            @WebParam(name = "SystemTag", targetNamespace = "http://tempuri.org/")
            String systemTag,
            @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
            String sign
    );

    @WebResult(name = "OpenMailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OpenMail", targetNamespace = "http://tempuri.org/", className = "OpenMail")
    @WebMethod(operationName = "OpenMail", action = "http://tempuri.org/OpenMail")
    @ResponseWrapper(localName = "OpenMailResponse", targetNamespace = "http://tempuri.org/", className = "OpenMailResponse")
    public StateInfo openMail(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );

    @WebResult(name = "UpdateUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://tempuri.org/", className = "UpdateUser")
    @WebMethod(operationName = "UpdateUser", action = "http://tempuri.org/UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://tempuri.org/", className = "UpdateUserResponse")
    public StateInfo updateUser(
            @WebParam(name = "userInfo", targetNamespace = "http://tempuri.org/")
            UserInfo userInfo
    );
}
